= Convencións

== Acerca da API
Nos seguintes capítulos atopará a API de cada un dos contratos abstractos que se referenciaron no momento de construir esta documentación,
seguindo unha xerarquía moi clara centrada no contrato que se pretende documentar.
A documentación se extrae dos nodos `<documentation>` do mesmo arquivo do contrato,
amosándose un *WARNING* onde falte a documentación.

A continuación pode atopar un resume da xerarquía da documentación da API:

* Service. Se describe o contrato a partires da documentación do wsdl.
O identificador do contrato se extrae do atributo *name* do mesmo.
** PortType. Se describen un por un todos os *porType* do contrato.
*** Operation. Se describen unha por unha todas as *operation* do contrato.
**** input. Se describe o parámetro *input* da operación, se existe.
***** part. Se describen un por un os distintos *part* do parámetro.
**** output. Se describe o parámetro *output* da operación, se existe.
***** part. Se describen un por un os distintos *part* do parámetro.

[plantuml, format="svg"]
----
skinparam Legend {
	BackgroundColor transparent
	BorderColor transparent
	FontName Courier
	FontSize 14
}
legend
Service (1)
|_ PortType (2)
  |_ Operation (3)
    |_ input (4)
      |_ part (5)
    |_ output (6)
      |_ part (7)
end legend
----

. Se describe o servizo a partires da documentación do wsdl. O identificador do contrato se extrae do atributo *name* do mesmo.
. Se describen un por un todos os *porType* do contrato.
. Se describen unha por unha todas as *operation* do contrato.
. Se describe o parámetro *input* da operación, se existe.
. Se describen un por un os distintos *part* do parámetro.
. Se describe o parámetro *output* da operación, se existe.
. Se describen un por un os distintos *part* do parámetro.

== Lenda das seccións 'Namespaces'
As distintas seccións que levan por título *Namespaces* e que enumeran a lista de namespaces usados no servizo,
posúen todas elas a seguinte lenda:

.Lenda
[%autowidth,frame=none,grid=cols,stripes=none,caption=]
|===
|*A*: attributeFormDefault +
*E*: elementFormDefault|{icon-enabled} => `qualified` +
{icon-disabled} => `unqualified` +
{icon-unSetted} => `descoñecido`
|===
